apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bpbmr2iba-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bpbmr2iba-go 
  name: bpbmr2iba-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bpbmr2iba-go 
